api_platform:
  title : 'Bilemo API'
  version : '1.0'
  formats:
      jsonld:   ['application/ld+json']
      jsonhal:  ['application/hal+json']
      jsonapi:  ['application/vnd.api+json']
      json:     ['application/json']
      html:     ['text/html']
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  http_cache:
    invalidation:
      enabled: true
    public: true
  defaults:
    cache_headers:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']

